/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Fertig": "Fertig",
    "Laden …": "Laden …",
    "Karte": "Karte",
    "Satellit": "Satellit",
    "Hybrid": "Hybrid",
    "Kartentitel wird hier angezeigt  ": "Kartentitel wird hier angezeigt  ",
    "Nur Markierungen anzeigen mit:": "Nur Markierungen anzeigen mit:",
    "Titel:": "Titel:",
    "Beschreibung:": "Beschreibung:",
    "Fehler beim Abfragen der Karteninformationen.": "Fehler beim Abfragen der Karteninformationen.",
    "Das Quelldokument konnte nicht verarbeitet werden.": "Das Quelldokument konnte nicht verarbeitet werden.",
    "Karten-API-Schlüssel in den Widget-Attributen festlegen.": "Karten-API-Schlüssel in den Widget-Attributen festlegen.",
    "Schlüssel abfragen": "Schlüssel abfragen",
    "Fehler beim Laden des Karten-API.": "Fehler beim Laden des Karten-API.",
    "Weitere Informationen …": "Weitere Informationen …"
};
