/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Datum": "Datum",
    "Fertig": "Fertig",
    "Täglicher RSS-Feed": "Täglicher RSS-Feed",
    "Laden": "Laden",
    "Ohne Titel": "Ohne Titel",
    "Der Artikeltitel wird hier angezeigt.": "Der Artikeltitel wird hier angezeigt.",
    "Der Artikelinhalt wird hier angezeigt.": "Der Artikelinhalt wird hier angezeigt.",
    "Fehler": "Fehler",
    "Keine Feed-URL verfügbar.": "Keine Feed-URL verfügbar.",
    "Der Feed wurde nicht verstanden.": "Der Feed wurde nicht verstanden.",
    "Laden eines gültigen Feeds fehlgeschlagen.": "Laden eines gültigen Feeds fehlgeschlagen.",
    "Kein <Channel>-Element im Feed.": "Kein <Channel>-Element im Feed.",
    "Kein <Feed>-Element im Atom-Feed.": "Kein <Feed>-Element im Atom-Feed."
};
