/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Mein RSS-Feed": "Mein RSS-Feed",
    "Neue URL: ": "Neue URL: ",
    "Festlegen": "Festlegen",
    "Feed-URLs: ": "Feed-URLs: ",
    "Artikellänge": "Artikellänge",
    "Zurücksetzen": "Zurücksetzen",
    "Fertig": "Fertig",
    "Feed ungültig": "Feed ungültig",
    "%s ist anscheinend kein gültiger RSS- oder Atom-Feed.": "%s ist anscheinend kein gültiger RSS- oder Atom-Feed.",
    "Keine Objekte gefunden": "Keine Objekte gefunden",
    "Der Feed enthält keine Einträge.": "Der Feed enthält keine Einträge.",
    "Keine Treffer zu diesen Suchbegriffen.": "Keine Treffer zu diesen Suchbegriffen.",
    "Keine anzuzeigenden Objekte": "Keine anzuzeigenden Objekte",
    "Der Feed enthält keine Einträge zu den angegebenen Kriterien.": "Der Feed enthält keine Einträge zu den angegebenen Kriterien.",
    "Laden": "Laden",
    "%s neu": "%s neu",
    "Kein Feed angegeben": "Kein Feed angegeben",
    "Gültige Feed-URL eingeben.": "Gültige Feed-URL eingeben."
};
