/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {

// Button strings
    "Fertig": "Fertig",
    "Abonnieren": "Abonnieren",
    "Mein Podcast": "Mein Podcast",
    "Beschreibung der Folge": "Beschreibung der Folge",
    "Datum der Folge": "Datum der Folge",
    "Name der Folge": "Name der Folge",

// Days of the week
    "Sonntag": "Sonntag",
    "Montag": "Montag",
    "Dienstag": "Dienstag",
    "Mittwoch": "Mittwoch",
    "Donnerstag": "Donnerstag",
    "Freitag": "Freitag",
    "Samstag": "Samstag",

// Months of the year
    "Januar": "Januar",
    "Februar": "Februar",
    "März": "März",
    "April": "April",
    "Mai": "Mai",
    "Juni": "Juni",
    "Juli": "Juli",
    "August": "August",
    "September": "September",
    "Oktober": "Oktober",
    "November": "November",
    "Dezember": "Dezember",

// Information strings
    "Kein Podcast unter dieser URL": "Kein Podcast unter dieser URL",
    "Kein Podcast angegeben": "Kein Podcast angegeben",
    "Kein Folgentitel verfügbar": "Kein Folgentitel verfügbar",
    "Keine Folgenbeschreibung verfügbar": "Keine Folgenbeschreibung verfügbar",
    "Datum ungültig oder nicht verfügbar": "Datum ungültig oder nicht verfügbar",
    "Über diesen Podcast:": "Über diesen Podcast:",
    "Laden": "Laden",
    "Keine Podcast-Beschreibung verfügbar": "Keine Podcast-Beschreibung verfügbar",
    "Kein Podcast verfügbar": "Kein Podcast verfügbar"
};
